name: Primer workflow

on: push

jobs:
  hola_mundo:
    runs-on: ubuntu-latest

    steps:
      - name: Bajar código
        uses: actions/checkout@v4
      - name: Probar código
        run: python3 main.py
      - name: Crear imagen Docker
        run: docker build -t ipalacios017/holamundo .
      - name: Probar contenedor
        run: docker run ipalacios017/holamundo
